### ISSUE TITLE
Recipe Page

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/How-To-Christmas#1]
As a user
I want to browse a list of festive recipes 
So I could find out what to cook on Christmas

**Acceptance Criteria:**

- [ ] each recipe should have ingredients
- [ ] each recipe should have instructions
- [ ] each recipe should have pictures

**Tasks:**

- [ ] to build html 
- [ ] style the page
