### ISSUE TITLE
Gifts: Sections

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/How-To-Christmas#10]
As a USER
I want to see different sections 
So I could see appropriately gift idea for different people

**Acceptance Criteria:**

- [x] have different sections for different target audiences
- [x] have a section for him
- [x] have a section for her

- [x] other sections:
- [x] child
- [x] DIY

**Tasks:**

- [x] use bootstrap accordions to create different sections
