### ISSUE TITLE
Gifts: For Her Section

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/How-To-Christmas#11]
As a USER
I want to see a for her section
So I could see what gifts to buy for a female friend

**Acceptance Criteria:**

- [x] have a for him section
- [x] provide ideas for gifts for males

**Tasks:**

- [x] create bootstrap cards for gift ideas
