### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/How-To-Christmas#2]
As a user
I want a navigation bar
So I could navigate to each page easily

**Acceptance Criteria:**

- [x] nav bar with links to each page
- [x] icon to home page
- [x] responsive

**Tasks:**

- [x] create responsive navbar with html, bootstrap and css
- [x] add nav links to pages
