### ISSUE TITLE
Gift Ideas

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/How-To-Christmas#3]
As a user
I want to see gift ideas
So I could find inspiration on what to gift on Christmas

**Acceptance Criteria:**

- [x] lists for him/her/children
- [x] 3+ ideas for each category
- [x] tabs for each category

**Tasks:**

- [x] create html lists for each category
- [x] use bootstrap to create tabs
