### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/How-To-Christmas#5]
As a user
I want to see a Home page
So I could be welcomed to the website

**Acceptance Criteria:**

- [ ] welcome message
- [ ] hero image
- [ ] links to pages

**Tasks:**

- [ ] create hero image with welcome message
- [ ] create links to other pages

**Comment by violaberg** [comment]
Hero image replaced with 3D animation
