### ISSUE TITLE
Gift List

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/How-To-Christmas#86]
As a USER
I want to make a gift list
So I could remember what gifts I want to buy

**Acceptance Criteria:**

- [ ] create a gift list
- [ ] add and remove items from the gift list

**Tasks:**

- [ ] create gift list modal
- [ ] create functions to add and remove items from gift list
