### ISSUE TITLE
For Kids Section

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/How-To-Christmas#87]
As a USER
I want to see a for kids section
So I could see what gifts to buy for a kids

**Acceptance Criteria:**

- [x] have a for kids section
- [x] provide ideas for gifts for kids

**Tasks:**

- [x] create bootstrap cards for gift ideas
