### ISSUE TITLE
Gifts: For Him Section

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/How-To-Christmas#9]
As a USER
I want to see a for him section
So I could see what gifts to buy for a male friend

**Acceptance Criteria:**

- [x] have a for him section
- [x] provide ideas for gifts for males

**Tasks:**

- [x] create bootstrap cards for gift ideas
