### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by violaberg** [KelvinC181/How-To-Christmas#94]
As a USER
I want to learn about the team behind the site
So I can appreciate their efforts and creativity.

**Acceptance Criteria:**

- Responsive page
- Each team member has their own card
- Member's image, info and links present

**Tasks:**

- [x] Create template
- [x] Add team member cards
- [x] Style accordingly to project
- [x] Add images, info and links
