### ISSUE TITLE
Gifts: Amazon

### ISSUE THREAD

**Issue by KelvinC181** [KelvinC181/How-To-Christmas#97]
As a USER
I want to see some amazon products
So I could have a approximate idea for what I can get on amazon

**Acceptance Criteria:**

- [ ] create section for amazon gifts
- [ ] show Christmas themed gifts from amazon

**Tasks:**

- [ ] create a section fetching product data using api from amazon

- unable to find appropriate api
